version: "3"

services:
  backend:
    build: .
    image: employee-manager
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - go-network
    restart: on-failure

  mysqldb:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=employee_manage
      - MYSQL_ROOT_PASSWORD=tF8jtP#zdz
      - MYSQL_USER=mynamebvh
      - MYSQL_PASSWORD:tF8jtP#zdz
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - go-network

  redis:
    image: redis:7
    ports:
      - '6382:6379'
    command: redis-server --requirepass !CnJb%IcJqew
    
volumes:
  dbdata:

networks:
  go-network:
    driver: bridge